import {createRoom,view,shuffle} from '@/lib/tambola';
import type {Room} from '@/lib/tambola';
import {database,cookie,identity,reply,checkOrigin} from '@/lib/rooms';
export async function POST(request:Request){
 try{checkOrigin(request);const body=await request.json() as {name?:unknown;code?:unknown};const name=typeof body.name==='string'?body.name.trim():'';if(!name||name.length>20)throw Error('Enter a name of 1–20 characters.');const token=cookie(request)??Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');const id=await identity(token),now=Date.now();const secure=new URL(request.url).protocol==='https:';
 if(body.code!==undefined){const code=String(body.code).trim().toUpperCase();if(!/^[A-Z]{6}$/.test(code))throw Error('Enter a six-letter room code.');for(let i=0;i<8;i++){const row=await database().prepare('SELECT state,revision FROM rooms WHERE code=?').bind('T'+code).first<{state:string;revision:number}>();if(!row)throw Error('Tambola room not found.');const room=JSON.parse(row.state) as Room;let p=room.players.find(p=>p.id===id);if(p){p.name=name;p.seen=now}else{if(room.players.length>=12)throw Error('This room is full.');room.players.push({id,name,seen:now})}const result=await database().prepare('UPDATE rooms SET state=?,revision=revision+1 WHERE code=? AND revision=?').bind(JSON.stringify(room),'T'+code,row.revision).run();if(result.meta.changes===1)return reply({...view(room,id,now),revision:row.revision+1},200,token,secure)}throw Error('The room is busy. Please try again.');}
 for(let i=0;i<5;i++){const code=shuffle('ABCDEFGHJKLMNPQRSTUVWXYZ'.split('')).slice(0,6).join('');const room=createRoom(code,{id,name,seen:now});const result=await database().prepare('INSERT INTO rooms(code,state,revision) VALUES(?,?,0) ON CONFLICT(code) DO NOTHING').bind('T'+code,JSON.stringify(room)).run();if(result.meta.changes===1)return reply(view(room,id,now),201,token,secure)}throw Error('Could not create the room.');
 }catch(e){return reply({error:e instanceof Error?e.message:'Room unavailable.'},400)}
}
